packages:
  - frontend
  - backend
  - packages/*

allowBuilds:
  '@prisma/engines': true
  prisma: true
  argon2: true
  msgpackr-extract: true
  '@scarf/scarf': false
  sharp: true
  unrs-resolver: false
