import { sql } from "drizzle-orm";
import { boolean, customType, numeric, timestamp, uuid, integer, varchar } from "drizzle-orm/pg-core";

/**
 * Column builders reused across every table.
 *
 * Consistency here is not cosmetic. RLS policies are generated by scanning for
 * a `tenant_id` column (see sql/rls.sql), the sync engine keys off `updated_at`,
 * and soft deletes are what make sync tombstones possible. A table that spells
 * any of these differently silently opts out of all three.
 *
 * ---------------------------------------------------------------------------
 * THE COLUMN GROUPS ARE FUNCTIONS, NOT OBJECTS. Spread them as `...timestamps()`.
 *
 * Drizzle column builders are mutable and carry per-table state. A shared
 * object literal hands every table the SAME builder instances, so anything
 * resolved at build time — most visibly a constraint name — is computed once
 * and reused everywhere. `clientId: uuid().unique()` in a shared literal
 * emitted `payments_clientId_unique` on all four syncable tables, and the
 * migration died on the second CREATE TABLE.
 *
 * A factory returns fresh builders per table. Keep it that way.
 * ---------------------------------------------------------------------------
 */

// -----------------------------------------------------------------------------
// Custom types
// -----------------------------------------------------------------------------

/** Postgres `tsvector`. Always a generated column — never written directly. */
export const tsvector = customType<{ data: string; driverData: string }>({
  dataType() {
    return "tsvector";
  },
});

/**
 * DECIMAL(12,4) surfaced to TypeScript as a string.
 *
 * `numeric` with `mode: "string"` is deliberate. Drizzle's default for numeric
 * is a JS number, which loses precision above 2^53 and cannot represent 0.1.
 * Amounts move as strings between Postgres and the app and are only converted
 * inside Money helpers. Never do arithmetic on these directly.
 */
export const money = (name?: string) =>
  name
    ? numeric(name, { precision: 12, scale: 4, mode: "string" })
    : numeric({ precision: 12, scale: 4, mode: "string" });

/** Quantities carry decimals too — 2.5 metres of cable, 0.75 kg of solder. */
export const quantity = (name?: string) =>
  name
    ? numeric(name, { precision: 12, scale: 4, mode: "string" })
    : numeric({ precision: 12, scale: 4, mode: "string" });

/** Percentages: DECIMAL(5,2), so 0.00 - 999.99. */
export const percent = (name?: string) =>
  name
    ? numeric(name, { precision: 5, scale: 2, mode: "string" })
    : numeric({ precision: 5, scale: 2, mode: "string" });

// -----------------------------------------------------------------------------
// Column groups
// -----------------------------------------------------------------------------

export const primaryId = () => uuid().primaryKey().defaultRandom();

/**
 * Timestamps present on every table.
 *
 * `updatedAt` is maintained by a database trigger (sql/triggers.sql), not by
 * the application. The POS sync engine pages through changes ordered by
 * updated_at; a row modified by a manual SQL fix or a bulk price update that
 * forgot to touch the column would never sync.
 */
export const timestamps = () => ({
  createdAt: timestamp({ withTimezone: true, mode: "date" })
    .notNull()
    .default(sql`now()`),
  updatedAt: timestamp({ withTimezone: true, mode: "date" })
    .notNull()
    .default(sql`now()`),
  version: integer().notNull().default(1),
});

/**
 * Soft delete.
 *
 * Rows referenced by financial history are never hard-deleted — an invoice from
 * last year must still render its product names. It also gives the sync engine
 * something to send: a row that simply vanished from a query result is
 * indistinguishable from one that was never sent, so deletes travel as
 * tombstones (`deletedAt IS NOT NULL`).
 */
export const softDelete = () => ({
  deletedAt: timestamp({ withTimezone: true, mode: "date" }),
});

/**
 * `tenantScope` lives in ./tenants.ts, not here.
 *
 * It has to reference `tenants.id`, and importing that table into this file
 * would create a cycle — every schema file imports these builders, and
 * tenants.ts is a schema file. drizzle-kit transpiles to CJS before evaluating,
 * where such a cycle surfaces as a temporal-dead-zone ReferenceError at
 * generate time rather than a compile error.
 */

export const activeFlag = () => ({
  isActive: boolean().notNull().default(true),
});

/**
 * Fields on any record a POS terminal can create while offline.
 *
 * `localId` is minted on the terminal and is the idempotency key: the server
 * upserts on it, so replaying a push after a timeout cannot double-book a sale.
 * `deviceId` records which terminal, `syncedAt` is null until the row has been
 * acknowledged. `syncStatus` tracks the sync state.
 */
export const syncable = () => ({
  localId: uuid(),
  deviceId: uuid(),
  syncedAt: timestamp({ withTimezone: true, mode: "date" }),
  syncStatus: varchar({ length: 20 }).notNull().default("pending"),
});
